### ISSUE TITLE
2020: Announcement e-mail

### ISSUE THREAD

**Issue by pspacek** [dns-violations/dnsflagday#145]
Proposed text:

---
Dear DNS people.

We are happy to announce next step for DNS Flag Day 2020.

Latest measurements indicate that practical breakage caused by the proposed change is tiny [1]. In other words we can conclude that the Internet is ready for the change.

The long delayed DNS Flag Day will become effective on 2020-10-01 (October 1st 2020)!

Detailed information including test tools and technical description of the change can be found at https://dnsflagday.net/2020/ .

[1] https://github.com/dns-violations/dnsflagday/issues/139#issuecomment-673489183
---

Do not hesitate to propose changes.

**Comment by vixie** [comment]
i propose that:

1. this not be called a flag day. this use cheapens that term.

2. 1232 not be recommended. use 1000 or 1400 or some arbitrary value, 
because 1232 is arbitrary but is meant to sound otherwise.

3. this not be done at all. instead work with fujiwara on ending 
fragmentation altogether.

re:

Petr Špaček wrote on 2020-09-08 00:55:
>
> Do not hesitate to propose changes.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by pspacek** [comment]
I'm sorry, the e-mail was already sent but I forgot to close this issue!

Of course 1232 is not set in stone and implementations will evolve but that have been rehashed several times already and I do not see point in repeating it here.
