### ISSUE TITLE
All tests fail for a domain when one of its nameservers is just offline

### ISSUE THREAD

**Issue by stephanbosch** [dns-violations/dnsflagday#28]
Tests fail with a timeout or connection refusal (tcp). I'd expect this to show some orange message indicating that the offline server could not be tested, rather than reporting that the domain is violating the standards.

**Comment by pspacek** [comment]
Hmm, at very best it could be reported as "slow" (rating 3/4 where 4 is "dead"), but I do not think it is worth the effort.

**Comment by vcunat** [comment]
When different IPs have different properties, I could imagine showing like 25% "STOP" + 75% "GO", but in any case there's the link to technical details...

**Comment by fleish** [comment]
I may have spoken too soon. I'm still looking into the reason(s) why I am getting intermittent failures with the tool, which is difficult to say with authority since I don't have access to the source network where the tests are being run from. I also tried running genreport myself, but it just hangs when I run it.

**Comment by Habbie** [comment]
genreport needs a domain name on stdin.

**Comment by Habbie** [comment]
Well, what's on fd 4?

**Comment by pspacek** [comment]
The whole point it so make servers responsive and eliminate timeouts which are hard to deal with so it is pointless to ignore some of the timeouts.
